### ISSUE TITLE
[Bug] 로딩 페이지에서 무한 루프

### ISSUE THREAD

**Issue by gclogs** [osamhack2022/WEB_ArmyReport_Thi-Key-Cha#18]
### AuthLoadUser.jsx 파일
```tsx
import React, { useEffect, useState } from 'react';
import AuthLoadBackground from './AuthLoadBackground'
import useHeader from '../base/hooks/useHeader';

const AuthLoadUser = () => {
  const { user } = useHeader();
  const [loading, setLoading] = useState(true);

  const loadUser = async () => {
    setLoading(true);
    try {
      if (user.uid) {
        setLoading(false);
        window.location.href = '/home';
      } else {
        setLoading(false);
        window.location.href = '/';
      }
      setLoading(false);
    } catch(e) {
      console.log(e);
    }
  }

  useEffect(() => {
    loadUser();
  }, [])

  return (
    <>
      {loading ? <AuthLoadBackground /> : null}
    </>
  )
}

export default AuthLoadUser;
```

- 문제의 컴포넌트
1. 유저 검증 로직이 loadUser 함수에서 이루어 지는데,
2. 무엇 때문인지 모르겠지만 계속되는 리렌더링 현상으로, `setTimeout`으로 감싸서 다시 시도해보았지만, 
    - 무한루프가 걸려 `[React] Too many re-renders. React limits the number of renders to prevent an infinite loop.` 에러가 나타났다.
    - [[Error] Too many re-renders.](https://born-dev.tistory.com/4) 해당 블로그에서는 useCallback() 으로 감싸라고 한다.
    - **우선적으로 시도해보고 이슈 수정하도록 하겠다.**

**Comment by Sunja-An** [comment]
A)
* loading 변수가 setLoading(true) 로 인해 계속해서 true 값이 들어가므로 loading 이 멈추지않는 것이 아닌지..
react 의 lifecycle 을 찾아보시면 state 가 바뀔시에 useEffect 는 계속해서 동작한다 라고 이해했습니다.
그래서 setloading 을 통해서 useEffect 2번째 인자에 다른 변수를 할당해주는게 어떤가 싶습니다.
useEffect(() => { }, [] ); 

>Reference
https://dmitripavlutin.com/react-useeffect-infinite-loop/
