### ISSUE TITLE
[Bug] Firebase path is Empty :(

### ISSUE THREAD

**Issue by Sunja-An** [osamhack2022/WEB_ArmyReport_Thi-Key-Cha#27]
| **Firebase Error**

Location : PostLetterWrite.jsx
Content : FirebaseError: Function collection() cannot be called with an empty path.

마음의 편지 작성 시, 보내기 버튼 눌렀을 경우에 collection 이 빈 경로로 나온다고 뜹니다.

@gclogs

**Comment by gclogs** [comment]
PostViwer 파일 내부 코드에 coll={} 프로퍼티가 있는데 거기 내부에 coll="path" 입력하시면 됩니다.
마음의 편지는 post-letters
건의사항은 post-suggets
