### ISSUE TITLE
유저들의 소속부대 코드 과정에 있어 질문있습니다.

### ISSUE THREAD

**Issue by Sunja-An** [osamhack2022/WEB_ArmyReport_Thi-Key-Cha#8]
## 소속부대 코드 작성
" 문제점 - 소속부대 같은 경우, Select 폼으로 부대의 조합이 가능하나 이것을 딕셔너리 배열로 만들자니, 가독성이 매우 떨어집니다.

* 혹여나 이에 대해서 시간나실 때 클래스로 작성해서 사용법 알려주실 수 있는지.. 여쭤보고 싶네용 ㅎㅎ.. ;)

**Comment by gclogs** [comment]
인터페이스나 클래스 같은 경우는 설계도를 만드는 것에 불과합니다.
재사용성 및 중복 방지 등의 장점은 있지만 굳이 필요한지 의문입니다.

p.s.딕셔너리 배열로 만들지 않고 따로 서버에서 json 데이터를 받아오는 방법도 있긴 한데... 그렇게 하시는게 더 편하실겁니다.

**Comment by Sunja-An** [comment]
서버에서 json 데이터를 받아오는게 파이어베이스에서 데이터를 만들고 만든 데이터를 바탕으로 코드 조합을 하는지?
